##
## Variable Definitions for EventCatalog-Sandbox
##

variable "region" {
  description = "The region to use for the Terraform run"
  default     = ""
}

variable "profile" {
  description = "The local IAM profile to use for the Terraform run"
  default     = ""
}

variable "fqdn" {
  description = "Fully qualified domain name that will be the host domain name to access the EventCatalog"
  default     = ""
}

variable "alt_fqdn" {
  description = "Fully qualified domain name that will be an alternate host domain name to access the EventCatalog"
  default     = ""
}

variable "zone_id" {
  description = "The route53 zone id for the domain zone of the FQDNs"
  default     = ""
}

variable "zone_name" {
  description = "The route53 zone name for the domain zone of the FQDNs"
  default     = ""
}

variable "lambda_file_name" {
  description = "The name of the lambda function file that was generated by the Widen/cloudfront-auth project"
  default     = ""
}

variable "lambda_name" {
  description = "The name of the lambda function that will be created"
  default     = "eventcatalog-lambda-function"
}
